#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses

awk '
$1 == "127.0.0.1" && $2 == "localhost" {
    print "127.0.0.2 localhost"
    next
}
$2 == "facebook.com" {
    next
}
{ print }
END {
    print "8.8.8.8 facebook.com"
}
' /etc/hosts > /tmp/hosts.new

cat /tmp/hosts.new > /etc/hosts
rm -f /tmp/hosts.new